// GENERATED by scripts/generate-pwa-assets.mjs — do not edit by hand.
// iOS matches a launch image on an exact device-width/height/DPR/orientation query; anything
// unmatched simply gets a blank screen.
export const APPLE_SPLASH: { href: string; media: string }[] = [
  {
    "href": "/splash/430x932@3x-portrait.png",
    "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "href": "/splash/430x932@3x-landscape.png",
    "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
  },
  {
    "href": "/splash/393x852@3x-portrait.png",
    "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "href": "/splash/393x852@3x-landscape.png",
    "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
  },
  {
    "href": "/splash/428x926@3x-portrait.png",
    "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "href": "/splash/428x926@3x-landscape.png",
    "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
  },
  {
    "href": "/splash/390x844@3x-portrait.png",
    "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "href": "/splash/390x844@3x-landscape.png",
    "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
  },
  {
    "href": "/splash/375x812@3x-portrait.png",
    "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "href": "/splash/375x812@3x-landscape.png",
    "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
  },
  {
    "href": "/splash/414x896@3x-portrait.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "href": "/splash/414x896@3x-landscape.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
  },
  {
    "href": "/splash/414x896@2x-portrait.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "href": "/splash/414x896@2x-landscape.png",
    "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
  },
  {
    "href": "/splash/414x736@3x-portrait.png",
    "media": "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    "href": "/splash/414x736@3x-landscape.png",
    "media": "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
  },
  {
    "href": "/splash/375x667@2x-portrait.png",
    "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "href": "/splash/375x667@2x-landscape.png",
    "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
  },
  {
    "href": "/splash/1024x1366@2x-portrait.png",
    "media": "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "href": "/splash/1024x1366@2x-landscape.png",
    "media": "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
  },
  {
    "href": "/splash/834x1194@2x-portrait.png",
    "media": "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "href": "/splash/834x1194@2x-landscape.png",
    "media": "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
  },
  {
    "href": "/splash/834x1112@2x-portrait.png",
    "media": "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "href": "/splash/834x1112@2x-landscape.png",
    "media": "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
  },
  {
    "href": "/splash/820x1180@2x-portrait.png",
    "media": "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "href": "/splash/820x1180@2x-landscape.png",
    "media": "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
  },
  {
    "href": "/splash/768x1024@2x-portrait.png",
    "media": "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    "href": "/splash/768x1024@2x-landscape.png",
    "media": "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
  }
];
