-- =============================================================
-- MIXED PAYMENTS (cash + online on one transaction) EVERYWHERE
--
-- Billing already supported a split; customer credit repayments, vendor payments
-- and salary payments did not — they stored a single `method` + `amount`.
--
-- THE TRAP THIS MIGRATION EXISTS TO AVOID: every finance reader bucketed those
-- three by `method = 'cash'` vs `method <> 'cash'`. Writing 'mixed' into the
-- tables WITHOUT rewriting the readers in the same breath would have sent the
-- ENTIRE amount to the online bucket ('mixed' <> 'cash' is true) and silently
-- corrupted cash-in-hand. So the columns, the writers and every reader move
-- together, in one migration. There is no intermediate state where the data is
-- expressible but unreadable.
--
-- The readers below are the LIVE definitions with only the bucketing lines
-- changed — generated by transforming pg_get_functiondef output rather than
-- retyped, because finance_report is 10k characters and a hand-copy is a
-- regression waiting to happen.
--
-- Shape follows `purchases`, which has worked this way since Phase 3: a
-- self-reconciling CHECK (cash + online = amount) makes an unbalanced split
-- impossible from ANY code path, not merely discouraged in the UI.
-- =============================================================


-- ── 1. Split columns on the three tables that lacked them ─────────────────────
alter table credit_payments
  add column if not exists cash_amount   numeric(12,2) not null default 0,
  add column if not exists online_amount numeric(12,2) not null default 0;

alter table vendor_payments
  add column if not exists cash_amount   numeric(12,2) not null default 0,
  add column if not exists online_amount numeric(12,2) not null default 0;

alter table salary_payments
  add column if not exists cash_amount   numeric(12,2) not null default 0,
  add column if not exists online_amount numeric(12,2) not null default 0;


-- ── 2. Backfill from the method that was recorded ─────────────────────────────
-- Every existing row was single-tender, so the whole amount belongs to whichever
-- bucket its method named. Done BEFORE the CHECK constraints, or every historical
-- row would violate them.
update credit_payments
   set cash_amount   = case when method = 'cash' then amount else 0 end,
       online_amount = case when method <> 'cash' then amount else 0 end
 where cash_amount = 0 and online_amount = 0;

update vendor_payments
   set cash_amount   = case when method = 'cash' then amount else 0 end,
       online_amount = case when method <> 'cash' then amount else 0 end
 where cash_amount = 0 and online_amount = 0;

update salary_payments
   set cash_amount   = case when method = 'cash' then amount else 0 end,
       online_amount = case when method <> 'cash' then amount else 0 end
 where cash_amount = 0 and online_amount = 0;


-- ── 3. Make an unbalanced split impossible ────────────────────────────────────
do $mig$
begin
  if not exists (select 1 from pg_constraint where conname = 'credit_payments_split_check') then
    alter table credit_payments add constraint credit_payments_split_check
      check (cash_amount >= 0 and online_amount >= 0 and cash_amount + online_amount = amount);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'vendor_payments_split_check') then
    alter table vendor_payments add constraint vendor_payments_split_check
      check (cash_amount >= 0 and online_amount >= 0 and cash_amount + online_amount = amount);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'salary_payments_split_check') then
    alter table salary_payments add constraint salary_payments_split_check
      check (cash_amount >= 0 and online_amount >= 0 and cash_amount + online_amount = amount);
  end if;

  -- salary_payments restricted method to ('cash','online'), so 'mixed' would be
  -- rejected outright however the rest of the system behaved.
  if exists (select 1 from pg_constraint where conname = 'salary_payments_method_check') then
    alter table salary_payments drop constraint salary_payments_method_check;
  end if;
end $mig$;

alter table salary_payments
  add constraint salary_payments_method_check
  check (method in ('cash', 'online', 'mixed'));


-- ── 4. Readers, rewritten in lockstep to sum the columns ─────────────────────
CREATE OR REPLACE FUNCTION public.finance_report(p_restaurant_id uuid, p_from timestamp with time zone, p_to timestamp with time zone)
 RETURNS TABLE(opening_cash numeric, opening_online numeric, opening_credit_to_us numeric, opening_credit_by_us numeric, sales_cash numeric, sales_online numeric, sales_card numeric, sales_credit numeric, sales_total numeric, purchases_cash numeric, purchases_online numeric, purchases_credit numeric, purchases_total numeric, customer_credit_created numeric, customer_credit_collected numeric, vendor_credit_created numeric, vendor_credit_paid numeric, customer_credit_outstanding numeric, vendor_credit_outstanding numeric, pending_customers integer, pending_vendors integer, salary_cash numeric, salary_online numeric, salary_advance numeric, salary_total numeric, salary_outstanding numeric, closing_cash numeric, closing_online numeric, closing_credit_to_us numeric, closing_credit_by_us numeric, has_opening boolean)
 LANGUAGE sql
 STABLE
AS $function$
  with
  seed as (
    select coalesce(o.opening_cash,0) cash, coalesce(o.opening_online,0) online,
           coalesce(o.effective_from,'-infinity'::timestamptz) eff,
           (o.restaurant_id is not null) present
    from (select 1) _ left join finance_openings o on o.restaurant_id = p_restaurant_id
  ),
  pay as (
    select
      sum(p.cash_amount) filter (where p.created_at >= (select eff from seed) and p.created_at < p_from) cash_before,
      sum(p.online_amount + coalesce(p.card_amount,0)) filter (where p.created_at >= (select eff from seed) and p.created_at < p_from) online_before,
      sum(p.cash_amount) filter (where p.created_at >= p_from and p.created_at < p_to) cash_in,
      sum(p.online_amount) filter (where p.created_at >= p_from and p.created_at < p_to) online_in,
      sum(coalesce(p.card_amount,0)) filter (where p.created_at >= p_from and p.created_at < p_to) card_in,
      sum(coalesce(p.total_amount,p.amount)) filter (where p.created_at >= p_from and p.created_at < p_to) total_in
    from payments p where p.restaurant_id = p_restaurant_id
  ),
  crp as (
    select
      sum(cp.cash_amount) filter (where cp.created_at >= (select eff from seed) and cp.created_at < p_from) cash_before,
      sum(cp.online_amount) filter (where cp.created_at >= (select eff from seed) and cp.created_at < p_from) online_before,
      sum(cp.cash_amount) filter (where cp.created_at >= p_from and cp.created_at < p_to) cash_in,
      sum(cp.online_amount) filter (where cp.created_at >= p_from and cp.created_at < p_to) online_in,
      sum(cp.amount) filter (where cp.created_at >= p_from and cp.created_at < p_to) collected,
      -- Credit-to-us legs. These have NO `eff` floor on purpose: the cash seed
      -- replaces pre-books cash movement, but a debt raised before the books
      -- opened is still owed today, and the customer's own opening term carries
      -- it. Flooring these would forgive it.
      sum(cp.amount) filter (where cp.created_at < p_from) collected_before,
      sum(cp.amount) filter (where cp.created_at < p_to)   collected_to
    from credit_payments cp where cp.restaurant_id = p_restaurant_id
  ),
  cr as (
    select
      sum(c.bill_amount - c.down_payment) filter (where c.created_at >= p_from and c.created_at < p_to) created,
      sum(c.bill_amount - c.down_payment) filter (where c.created_at < p_from) raised_before,
      sum(c.bill_amount - c.down_payment) filter (where c.created_at < p_to)   raised_to
    from credits c where c.restaurant_id = p_restaurant_id
  ),
  cust as (
    select coalesce(sum(balance),0) outstanding,
           count(*) filter (where balance > 0)::int pending,
           -- The pre-system anchor, dated at the account's creation.
           coalesce(sum(opening_balance) filter (where created_at < p_from),0) open_before,
           coalesce(sum(opening_balance) filter (where created_at < p_to),0)   open_to
    from credit_customers where restaurant_id = p_restaurant_id
  ),
  pur as (
    select
      sum(pu.cash_amount) filter (where pu.created_at >= (select eff from seed) and pu.created_at < p_from) cash_before,
      sum(pu.online_amount) filter (where pu.created_at >= (select eff from seed) and pu.created_at < p_from) online_before,
      sum(pu.cash_amount) filter (where pu.created_at >= p_from and pu.created_at < p_to) cash_out,
      sum(pu.online_amount) filter (where pu.created_at >= p_from and pu.created_at < p_to) online_out,
      sum(pu.credit_amount) filter (where pu.created_at >= p_from and pu.created_at < p_to) credit_out,
      sum(pu.total_amount) filter (where pu.created_at >= p_from and pu.created_at < p_to) total_out,
      -- Credit-by-us legs, unfloored for the same reason as the customer side.
      sum(pu.credit_amount) filter (where pu.created_at < p_from) owed_before,
      sum(pu.credit_amount) filter (where pu.created_at < p_to)   owed_to
    from purchases pu where pu.restaurant_id = p_restaurant_id
  ),
  vp as (
    select
      sum(s.cash_amount) filter (where s.created_at >= (select eff from seed) and s.created_at < p_from) cash_before,
      sum(s.online_amount) filter (where s.created_at >= (select eff from seed) and s.created_at < p_from) online_before,
      sum(s.cash_amount) filter (where s.created_at >= p_from and s.created_at < p_to) cash_out,
      sum(s.online_amount) filter (where s.created_at >= p_from and s.created_at < p_to) online_out,
      sum(s.amount) filter (where s.created_at >= p_from and s.created_at < p_to) paid,
      sum(s.amount) filter (where s.created_at < p_from) paid_before,
      sum(s.amount) filter (where s.created_at < p_to)   paid_to
    from vendor_payments s where s.restaurant_id = p_restaurant_id
  ),
  sal as (
    select
      sum(sp.cash_amount) filter (where sp.created_at >= (select eff from seed) and sp.created_at < p_from) cash_before,
      sum(sp.online_amount) filter (where sp.created_at >= (select eff from seed) and sp.created_at < p_from) online_before,
      sum(sp.cash_amount) filter (where sp.created_at >= p_from and sp.created_at < p_to) cash_out,
      sum(sp.online_amount) filter (where sp.created_at >= p_from and sp.created_at < p_to) online_out,
      sum(sp.amount) filter (where sp.kind = 'advance'  and sp.created_at >= p_from and sp.created_at < p_to) advance_out,
      sum(sp.amount) filter (where sp.created_at >= p_from and sp.created_at < p_to) total_out
    from salary_payments sp where sp.restaurant_id = p_restaurant_id
  ),
  ven as (
    select coalesce(sum(credit_balance),0) outstanding,
           count(*) filter (where credit_balance > 0)::int pending,
           coalesce(sum(opening_credit) filter (where created_at < p_from),0) open_before,
           coalesce(sum(opening_credit) filter (where created_at < p_to),0)   open_to
    from vendors where restaurant_id = p_restaurant_id
  ),
  owed as (
    select coalesce((select outstanding_liability from payroll_summary(p_restaurant_id, p_from, p_to)), 0) v
  ),
  calc as (
    select
      (select cash from seed) + coalesce((select cash_before from pay),0) + coalesce((select cash_before from crp),0)
        - coalesce((select cash_before from pur),0) - coalesce((select cash_before from vp),0)
        - coalesce((select cash_before from sal),0) open_cash,
      (select online from seed) + coalesce((select online_before from pay),0) + coalesce((select online_before from crp),0)
        - coalesce((select online_before from pur),0) - coalesce((select online_before from vp),0)
        - coalesce((select online_before from sal),0) open_online,

      -- The two credit balances, evaluated at each end of the period.
      (select open_before from cust) + coalesce((select raised_before from cr),0)
        - coalesce((select collected_before from crp),0) open_to_us,
      (select open_to from cust) + coalesce((select raised_to from cr),0)
        - coalesce((select collected_to from crp),0) close_to_us,
      (select open_before from ven) + coalesce((select owed_before from pur),0)
        - coalesce((select paid_before from vp),0) open_by_us,
      (select open_to from ven) + coalesce((select owed_to from pur),0)
        - coalesce((select paid_to from vp),0) close_by_us
  )
  select
    calc.open_cash::numeric, calc.open_online::numeric,
    calc.open_to_us::numeric, calc.open_by_us::numeric,
    coalesce((select cash_in from pay),0)::numeric,
    coalesce((select online_in from pay),0)::numeric,
    coalesce((select card_in from pay),0)::numeric,
    coalesce((select created from cr),0)::numeric,
    coalesce((select total_in from pay),0)::numeric,
    coalesce((select cash_out from pur),0)::numeric,
    coalesce((select online_out from pur),0)::numeric,
    coalesce((select credit_out from pur),0)::numeric,
    coalesce((select total_out from pur),0)::numeric,
    coalesce((select created from cr),0)::numeric,
    coalesce((select collected from crp),0)::numeric,
    coalesce((select credit_out from pur),0)::numeric,
    coalesce((select paid from vp),0)::numeric,
    (select outstanding from cust)::numeric,
    (select outstanding from ven)::numeric,
    (select pending from cust),
    (select pending from ven),
    coalesce((select cash_out from sal),0)::numeric,
    coalesce((select online_out from sal),0)::numeric,
    coalesce((select advance_out from sal),0)::numeric,
    coalesce((select total_out from sal),0)::numeric,
    (select v from owed)::numeric,
    (calc.open_cash + coalesce((select cash_in from pay),0) + coalesce((select cash_in from crp),0)
      - coalesce((select cash_out from pur),0) - coalesce((select cash_out from vp),0)
      - coalesce((select cash_out from sal),0))::numeric,
    (calc.open_online + coalesce((select online_in from pay),0) + coalesce((select card_in from pay),0)
      + coalesce((select online_in from crp),0)
      - coalesce((select online_out from pur),0) - coalesce((select online_out from vp),0)
      - coalesce((select online_out from sal),0))::numeric,
    calc.close_to_us::numeric, calc.close_by_us::numeric,
    (select present from seed)
  from calc;
$function$
;

revoke all on function finance_report(uuid, timestamptz, timestamptz) from public;
grant execute on function finance_report(uuid, timestamptz, timestamptz) to service_role;
CREATE OR REPLACE FUNCTION public.finance_transactions(p_restaurant_id uuid, p_from timestamp with time zone, p_to timestamp with time zone)
 RETURNS TABLE(occurred_at timestamp with time zone, kind text, party text, method text, amount numeric, reference text, cash_delta numeric, online_delta numeric, credit_to_us_delta numeric, credit_by_us_delta numeric, cash_after numeric, online_after numeric, credit_to_us_after numeric, credit_by_us_after numeric)
 LANGUAGE sql
 STABLE
AS $function$
  with
  opening as (
    select opening_cash oc, opening_online oo,
           opening_credit_to_us otu, opening_credit_by_us obu
    from finance_report(p_restaurant_id, p_from, p_to)
  ),

  moves as (
    -- A bill. The tendered split is real money; the gap up to the bill total is
    -- credit raised against the customer.
    select
      p.created_at occurred_at,
      'sale'::text kind,
      (select cc.name from credits c
         join credit_customers cc on cc.id = c.customer_id
        where c.payment_id = p.id limit 1) party,
      case
        when coalesce(p.total_amount,p.amount) - (p.cash_amount + p.online_amount + coalesce(p.card_amount,0)) > 0.005
          then case when p.cash_amount + p.online_amount + coalesce(p.card_amount,0) > 0.005
                    then 'partial' else 'credit' end
        when p.cash_amount > 0.005 and p.online_amount + coalesce(p.card_amount,0) > 0.005 then 'mixed'
        when p.online_amount > 0.005 then 'online'
        when coalesce(p.card_amount,0) > 0.005 then 'card'
        else 'cash'
      end::text method,
      coalesce(p.total_amount,p.amount) amount,
      case when p.bill_number is not null then 'Bill #' || p.bill_number else null end::text reference,
      p.cash_amount cash_delta,
      (p.online_amount + coalesce(p.card_amount,0)) online_delta,
      (coalesce(p.total_amount,p.amount) - (p.cash_amount + p.online_amount + coalesce(p.card_amount,0))) credit_to_us_delta,
      0::numeric credit_by_us_delta
    from payments p
    where p.restaurant_id = p_restaurant_id
      and p.created_at >= p_from and p.created_at < p_to

    union all

    -- Money received against an existing debt: cash in, receivable down. NOT new
    -- revenue — the bill was already counted when it was raised (accrual).
    select
      cp.created_at, 'credit_repayment',
      cc.name,
      case when cp.cash_amount > 0.005 and cp.online_amount > 0.005 then 'mixed' else cp.method::text end,
      cp.amount,
      cc.customer_code,
      cp.cash_amount,
      cp.online_amount,
      -cp.amount,
      0::numeric
    from credit_payments cp
    left join credit_customers cc on cc.id = cp.customer_id
    where cp.restaurant_id = p_restaurant_id
      and cp.created_at >= p_from and cp.created_at < p_to

    union all

    -- A supplier bill. Only the settled part leaves the till; the rest is a
    -- payable.
    select
      pu.created_at, 'purchase',
      v.name,
      pu.payment_method::text,
      pu.total_amount,
      pu.purchase_code,
      -pu.cash_amount,
      -pu.online_amount,
      0::numeric,
      pu.credit_amount
    from purchases pu
    left join vendors v on v.id = pu.vendor_id
    where pu.restaurant_id = p_restaurant_id
      and pu.created_at >= p_from and pu.created_at < p_to

    union all

    -- Paying a supplier down: money out AND the payable falls.
    select
      vp.created_at, 'vendor_payment',
      v.name,
      case when vp.cash_amount > 0.005 and vp.online_amount > 0.005 then 'mixed' else vp.method::text end,
      vp.amount,
      v.vendor_code,
      -vp.cash_amount,
      -vp.online_amount,
      0::numeric,
      -vp.amount
    from vendor_payments vp
    left join vendors v on v.id = vp.vendor_id
    where vp.restaurant_id = p_restaurant_id
      and vp.created_at >= p_from and vp.created_at < p_to

    union all

    -- Wages. Money out, no credit leg — payroll's own liability is reported
    -- separately and is not a vendor-style payable.
    select
      sp.created_at,
      case when sp.kind = 'advance' then 'salary_advance' else 'salary' end,
      ru.display_name,
      case when sp.cash_amount > 0.005 and sp.online_amount > 0.005 then 'mixed' else sp.method::text end,
      sp.amount,
      to_char(sp.salary_month, 'Mon YYYY'),
      -sp.cash_amount,
      -sp.online_amount,
      0::numeric,
      0::numeric
    from salary_payments sp
    left join restaurant_users ru on ru.id = sp.restaurant_user_id
    where sp.restaurant_id = p_restaurant_id
      and sp.created_at >= p_from and sp.created_at < p_to

    union all

    -- An account OPENED during the period carrying a balance from paper books.
    -- No money moves, but the debt is real from that moment and it lands in the
    -- closing balance — so without these two branches the running total falls
    -- short by exactly the carried amount. (Found by the reconciliation check:
    -- two live restaurants were off by precisely their vendors' opening credit.)
    select
      v.created_at, 'vendor_opening',
      v.name, 'credit'::text, v.opening_credit, v.vendor_code,
      0::numeric, 0::numeric, 0::numeric, v.opening_credit
    from vendors v
    where v.restaurant_id = p_restaurant_id
      and v.opening_credit > 0
      and v.created_at >= p_from and v.created_at < p_to

    union all

    select
      cc.created_at, 'customer_opening',
      cc.name, 'credit'::text, cc.opening_balance, cc.customer_code,
      0::numeric, 0::numeric, cc.opening_balance, 0::numeric
    from credit_customers cc
    where cc.restaurant_id = p_restaurant_id
      and cc.opening_balance > 0
      and cc.created_at >= p_from and cc.created_at < p_to
  )

  select
    m.occurred_at, m.kind, m.party, m.method, m.amount, m.reference,
    m.cash_delta, m.online_delta, m.credit_to_us_delta, m.credit_by_us_delta,
    ((select oc  from opening) + sum(m.cash_delta)         over w)::numeric,
    ((select oo  from opening) + sum(m.online_delta)       over w)::numeric,
    ((select otu from opening) + sum(m.credit_to_us_delta) over w)::numeric,
    ((select obu from opening) + sum(m.credit_by_us_delta) over w)::numeric
  from moves m
  -- `occurred_at` alone is not a total order — two movements can share an
  -- instant — so the running balance would be non-deterministic without a
  -- tie-break. Ordering the frame by (time, kind, reference) makes every read
  -- of the same period produce the same ledger.
  window w as (order by m.occurred_at, m.kind, m.reference
               rows between unbounded preceding and current row)
  order by m.occurred_at desc, m.kind, m.reference;
$function$
;

revoke all on function finance_transactions(uuid, timestamptz, timestamptz) from public;
grant execute on function finance_transactions(uuid, timestamptz, timestamptz) to service_role;
CREATE OR REPLACE FUNCTION public.payroll_summary(p_restaurant_id uuid, p_from timestamp with time zone, p_to timestamp with time zone, p_today_from timestamp with time zone DEFAULT NULL::timestamp with time zone, p_month_from timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS TABLE(period_salary numeric, period_advance numeric, period_total numeric, period_cash numeric, period_online numeric, today_total numeric, month_total numeric, all_time_total numeric, all_time_advance numeric, outstanding_liability numeric, staff_on_payroll integer)
 LANGUAGE sql
 STABLE
AS $function$
  with
  pay as (
    select
      coalesce(sum(amount) filter (where kind = 'salary'  and created_at >= p_from and created_at < p_to), 0) p_sal,
      coalesce(sum(amount) filter (where kind = 'advance' and created_at >= p_from and created_at < p_to), 0) p_adv,
      coalesce(sum(amount) filter (where created_at >= p_from and created_at < p_to), 0)                      p_tot,
      coalesce(sum(cash_amount) filter (where created_at >= p_from and created_at < p_to), 0) p_cash,
      coalesce(sum(online_amount) filter (where created_at >= p_from and created_at < p_to), 0) p_online,
      coalesce(sum(amount) filter (
        where created_at >= coalesce(p_today_from, date_trunc('day', now()))), 0)                              t_tot,
      coalesce(sum(amount) filter (
        where created_at >= coalesce(p_month_from, date_trunc('month', now()))), 0)                            m_tot,
      coalesce(sum(amount), 0)                                                                                a_tot,
      coalesce(sum(amount) filter (where kind = 'advance'), 0)                                                a_adv
    from salary_payments
    where restaurant_id = p_restaurant_id
  ),
  -- Every payroll month of every staff member, from the month they joined to the
  -- month we are in now. Left on calendar months deliberately: a payroll month is
  -- a month, not a trading day, and shifting it by a closing hour would be wrong.
  months as (
    select
      pr.restaurant_user_id,
      generate_series(
        date_trunc('month', pr.joining_date),
        date_trunc('month', now()),
        interval '1 month'
      )::date as month
    from staff_payroll pr
    join restaurant_users ru on ru.id = pr.restaurant_user_id
    where pr.restaurant_id = p_restaurant_id
      and ru.deleted_at is null
  ),
  owed as (
    select coalesce(sum(
      greatest(
        coalesce(sal.monthly_salary, 0) - coalesce(p.paid, 0),
        0
      )
    ), 0) v
    from months m
    left join lateral (
      select s.monthly_salary
        from staff_salaries s
       where s.restaurant_user_id = m.restaurant_user_id
         and s.effective_from <= m.month
       order by s.effective_from desc
       limit 1
    ) sal on true
    left join lateral (
      select coalesce(sum(sp.amount), 0) paid
        from salary_payments sp
       where sp.restaurant_user_id = m.restaurant_user_id
         and sp.restaurant_id = p_restaurant_id
         and sp.salary_month = m.month
    ) p on true
  ),
  headcount as (
    select count(*)::int v
    from staff_payroll pr
    join restaurant_users ru on ru.id = pr.restaurant_user_id
    where pr.restaurant_id = p_restaurant_id and ru.deleted_at is null and ru.is_active
  )
  select
    pay.p_sal::numeric, pay.p_adv::numeric, pay.p_tot::numeric,
    pay.p_cash::numeric, pay.p_online::numeric,
    pay.t_tot::numeric, pay.m_tot::numeric,
    pay.a_tot::numeric, pay.a_adv::numeric,
    owed.v::numeric,
    headcount.v
  from pay, owed, headcount;
$function$
;

revoke all on function payroll_summary(uuid, timestamptz, timestamptz, timestamptz, timestamptz) from public;
grant execute on function payroll_summary(uuid, timestamptz, timestamptz, timestamptz, timestamptz) to service_role;

-- ── 5. Purchases: a fully-paid cash+online bill is now expressible ───────────
-- The table and its CHECK always supported a split, but this function
-- OVERWROTE v_cash/v_online for any non-credit method, so the split only ever
-- opened up when part of the bill went on credit.
CREATE OR REPLACE FUNCTION public.record_purchase(p_restaurant_id uuid, p_vendor_id uuid, p_method text, p_cash numeric, p_online numeric, p_items jsonb, p_notes text, p_created_by uuid)
 RETURNS purchases
 LANGUAGE plpgsql
AS $function$
declare
  v_vendor   vendors;
  v_total    numeric := 0;
  v_paid     numeric := coalesce(p_cash, 0) + coalesce(p_online, 0);
  v_credit   numeric := 0;
  v_cash     numeric := coalesce(p_cash, 0);
  v_online   numeric := coalesce(p_online, 0);
  v_seq      int;
  v_purchase purchases;
  v_item     jsonb;
  v_count    int;
begin
  if p_method not in ('cash', 'online', 'credit', 'mixed') then
    raise exception 'INVALID_METHOD';
  end if;
  if v_cash < 0 or v_online < 0 then
    raise exception 'INVALID_AMOUNT';
  end if;

  select * into v_vendor
    from vendors
   where id = p_vendor_id and restaurant_id = p_restaurant_id
   for update;
  if not found then
    raise exception 'VENDOR_NOT_FOUND';
  end if;
  if not v_vendor.is_active then
    raise exception 'VENDOR_INACTIVE';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'NO_ITEMS';
  end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    if (v_item->>'quantity')::numeric <= 0 then
      raise exception 'INVALID_QUANTITY';
    end if;
    if (v_item->>'unit_cost')::numeric < 0 then
      raise exception 'INVALID_UNIT_COST';
    end if;

    select count(*) into v_count
      from products
     where id = (v_item->>'product_id')::uuid
       and restaurant_id = p_restaurant_id
       and is_active;
    if v_count = 0 then
      raise exception 'PRODUCT_NOT_FOUND';
    end if;

    v_total := v_total + round((v_item->>'quantity')::numeric * (v_item->>'unit_cost')::numeric, 2);
  end loop;

  if v_total <= 0 then
    raise exception 'INVALID_TOTAL';
  end if;

  if p_method = 'credit' then
    if v_paid >= v_total then
      raise exception 'NOTHING_ON_CREDIT';
    end if;
    v_credit := v_total - v_paid;
  else
    v_credit := 0;
    if p_method = 'mixed' then
      -- Caller supplied the split; it must reconcile to the bill exactly.
      if abs((v_cash + v_online) - v_total) > 0.005 then
        raise exception 'SPLIT_MISMATCH';
      end if;
    elsif p_method = 'cash' then
      v_cash := v_total; v_online := 0;
    else
      v_cash := 0; v_online := v_total;
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtext('purchase_seq:' || p_restaurant_id::text));
  select coalesce(max(seq_no), 0) + 1 into v_seq
    from purchases where restaurant_id = p_restaurant_id;

  insert into purchases (
    restaurant_id, seq_no, vendor_id, payment_method,
    total_amount, cash_amount, online_amount, credit_amount, notes, created_by
  )
  values (
    p_restaurant_id, v_seq, p_vendor_id, p_method::payment_method,
    v_total, v_cash, v_online, v_credit,
    nullif(btrim(coalesce(p_notes, '')), ''), p_created_by
  )
  returning * into v_purchase;

  insert into purchase_items (purchase_id, restaurant_id, product_id, quantity, unit_cost)
  select
    v_purchase.id,
    p_restaurant_id,
    (i->>'product_id')::uuid,
    (i->>'quantity')::numeric,
    (i->>'unit_cost')::numeric
  from jsonb_array_elements(p_items) i;

  update products p
     set last_unit_cost = x.unit_cost
    from (
      select distinct on ((i->>'product_id')::uuid)
             (i->>'product_id')::uuid as product_id,
             (i->>'unit_cost')::numeric as unit_cost
        from jsonb_array_elements(p_items) i
    ) x
   where p.id = x.product_id
     and p.restaurant_id = p_restaurant_id;

  -- The credit half of the bill becomes a debt to this vendor.
  if v_credit > 0 then
    update vendors
       set credit_balance = credit_balance + v_credit
     where id = p_vendor_id;
  end if;

  return v_purchase;
end;
$function$
;

revoke all on function record_purchase(uuid, uuid, text, numeric, numeric, jsonb, text, uuid) from public;
grant execute on function record_purchase(uuid, uuid, text, numeric, numeric, jsonb, text, uuid) to service_role;


-- ── 6. Writers: accept a split, defaulting to the old single-tender behaviour ─
-- Each old signature is DROPPED before the new one is created. Adding defaulted
-- parameters WITHOUT dropping would leave two candidates and make every existing
-- call ambiguous ("function ... is not unique") — the failure that nearly took
-- the Finance page down when payroll_summary gained parameters.
drop function if exists record_credit_payment(uuid, uuid, numeric, text, text, uuid);
CREATE OR REPLACE FUNCTION public.record_credit_payment(p_restaurant_id uuid, p_customer_id uuid, p_amount numeric, p_method text, p_notes text, p_received_by uuid, p_cash numeric DEFAULT NULL::numeric, p_online numeric DEFAULT NULL::numeric)
 RETURNS credit_customers
 LANGUAGE plpgsql
AS $function$
declare
  v_cust      credit_customers;
  v_applied   numeric;
  v_remaining numeric;
  v_bill      credits;
  v_take      numeric;
  v_cash      numeric;
  v_online    numeric;
begin
  -- `for update` serialises two cashiers taking money from the same customer.
  select * into v_cust
    from credit_customers
   where id = p_customer_id
     and restaurant_id = p_restaurant_id
     for update;
  if not found then
    raise exception 'CUSTOMER_NOT_FOUND';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'INVALID_AMOUNT';
  end if;
  if v_cust.balance <= 0 then
    raise exception 'NOTHING_OWED';
  end if;

  -- Never overpay. A hair over settles it exactly (rounding on the cashier's
  -- side); anything more is a mistake.
  if p_amount > v_cust.balance + 0.005 then
    raise exception 'AMOUNT_EXCEEDS_BALANCE';
  end if;
  v_applied := least(p_amount, v_cust.balance);

  -- One ledger row against the account — this is the payment history.

  -- Resolve the tender split. No split given → single-tender, derived from the
  -- method, i.e. precisely what this function did before.
  if p_cash is null and p_online is null then
    v_cash   := case when p_method = 'cash' then v_applied else 0 end;
    v_online := case when p_method = 'cash' then 0 else v_applied end;
  else
    v_cash   := coalesce(p_cash, 0);
    v_online := coalesce(p_online, 0);
    if v_cash < 0 or v_online < 0 then
      raise exception 'INVALID_AMOUNT';
    end if;
    if abs((v_cash + v_online) - v_applied) > 0.005 then
      raise exception 'SPLIT_MISMATCH';
    end if;
    -- Absorb sub-paisa rounding into cash so cash + online = amount EXACTLY and
    -- the CHECK constraint holds. Without this a 33.333/66.667 split fails.
    v_cash := v_applied - v_online;
  end if;

  insert into credit_payments (customer_id, credit_id, restaurant_id, amount, method,
                               cash_amount, online_amount, notes, received_by)
  values (
    p_customer_id, null, p_restaurant_id, v_applied, p_method::payment_method,
    v_cash, v_online,
    nullif(btrim(coalesce(p_notes, '')), ''), p_received_by
  );

  -- Allocate it across the open bills, oldest first, so each bill's status stays
  -- true. The account balance remains the single source of what is owed.
  --
  -- `seq_no` breaks ties: two bills raised in the same instant would otherwise
  -- have an arbitrary allocation order, so the same payment could settle a
  -- different bill on a re-read. seq_no is monotonic per restaurant, so FIFO is
  -- deterministic.
  v_remaining := v_applied;
  for v_bill in
    select * from credits
     where customer_id = p_customer_id
       and status <> 'fully_paid'
     order by created_at, seq_no
     for update
  loop
    exit when v_remaining <= 0;

    v_take := least(v_remaining, v_bill.bill_amount - v_bill.paid_amount);
    if v_take <= 0 then
      continue;
    end if;

    update credits
       set paid_amount = paid_amount + v_take,
           status = case when bill_amount - (paid_amount + v_take) <= 0.005
                         then 'fully_paid' else 'partially_paid' end,
           settled_at = case when bill_amount - (paid_amount + v_take) <= 0.005
                             then now() else null end
     where id = v_bill.id;

    v_remaining := v_remaining - v_take;
  end loop;

  update credit_customers
     set balance = balance - v_applied
   where id = p_customer_id
  returning * into v_cust;

  return v_cust;
end;
$function$
;

revoke all on function record_credit_payment(uuid, uuid, numeric, text, text, uuid, numeric, numeric) from public;
grant execute on function record_credit_payment(uuid, uuid, numeric, text, text, uuid, numeric, numeric) to service_role;

drop function if exists record_vendor_payment(uuid, uuid, numeric, text, text, uuid);
CREATE OR REPLACE FUNCTION public.record_vendor_payment(p_restaurant_id uuid, p_vendor_id uuid, p_amount numeric, p_method text, p_notes text, p_paid_by uuid, p_cash numeric DEFAULT NULL::numeric, p_online numeric DEFAULT NULL::numeric)
 RETURNS vendors
 LANGUAGE plpgsql
AS $function$
declare
  v_vendor  vendors;
  v_applied numeric;
  v_cash    numeric;
  v_online  numeric;
begin
  select * into v_vendor
    from vendors
   where id = p_vendor_id
     and restaurant_id = p_restaurant_id
     for update;
  if not found then
    raise exception 'VENDOR_NOT_FOUND';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'INVALID_AMOUNT';
  end if;
  if v_vendor.credit_balance <= 0 then
    raise exception 'NOTHING_OWED';
  end if;

  if p_amount > v_vendor.credit_balance + 0.005 then
    raise exception 'AMOUNT_EXCEEDS_BALANCE';
  end if;
  v_applied := least(p_amount, v_vendor.credit_balance);


  -- Resolve the tender split. No split given → single-tender, derived from the
  -- method, i.e. precisely what this function did before.
  if p_cash is null and p_online is null then
    v_cash   := case when p_method = 'cash' then v_applied else 0 end;
    v_online := case when p_method = 'cash' then 0 else v_applied end;
  else
    v_cash   := coalesce(p_cash, 0);
    v_online := coalesce(p_online, 0);
    if v_cash < 0 or v_online < 0 then
      raise exception 'INVALID_AMOUNT';
    end if;
    if abs((v_cash + v_online) - v_applied) > 0.005 then
      raise exception 'SPLIT_MISMATCH';
    end if;
    -- Absorb sub-paisa rounding into cash so cash + online = amount EXACTLY and
    -- the CHECK constraint holds. Without this a 33.333/66.667 split fails.
    v_cash := v_applied - v_online;
  end if;

  insert into vendor_payments (vendor_id, restaurant_id, amount, method,
                               cash_amount, online_amount, notes, paid_by)
  values (
    p_vendor_id, p_restaurant_id, v_applied, p_method::payment_method,
    v_cash, v_online,
    nullif(btrim(coalesce(p_notes, '')), ''), p_paid_by
  );

  update vendors
     set credit_balance = credit_balance - v_applied
   where id = p_vendor_id
  returning * into v_vendor;

  return v_vendor;
end;
$function$
;

revoke all on function record_vendor_payment(uuid, uuid, numeric, text, text, uuid, numeric, numeric) from public;
grant execute on function record_vendor_payment(uuid, uuid, numeric, text, text, uuid, numeric, numeric) to service_role;

drop function if exists record_salary_payment(uuid, uuid, date, numeric, text, text, text, uuid);
CREATE OR REPLACE FUNCTION public.record_salary_payment(p_restaurant_id uuid, p_staff_id uuid, p_month date, p_amount numeric, p_kind text, p_method text, p_notes text, p_by uuid, p_cash numeric DEFAULT NULL::numeric, p_online numeric DEFAULT NULL::numeric)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
declare
  v_cash      numeric;
  v_online    numeric;
  v_month     date;
  v_salary    numeric;
  v_paid      numeric;
  v_remaining numeric;
  v_id        uuid;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'INVALID_AMOUNT';
  end if;
  if p_kind not in ('advance', 'salary') then
    raise exception 'INVALID_KIND';
  end if;
  if p_method not in ('cash', 'online', 'mixed') then
    raise exception 'INVALID_METHOD';
  end if;

  v_month := date_trunc('month', coalesce(p_month, current_date))::date;

  -- Lock the payroll profile. Scoping by restaurant_id here is the tenant check:
  -- no profile of ours, no payment.
  perform 1
     from staff_payroll
    where restaurant_user_id = p_staff_id
      and restaurant_id = p_restaurant_id
      for update;
  if not found then
    raise exception 'PAYROLL_NOT_SET';
  end if;

  v_salary := salary_for_month(p_staff_id, v_month);
  if v_salary is null then
    raise exception 'SALARY_NOT_SET';
  end if;

  select coalesce(sum(amount), 0) into v_paid
    from salary_payments
   where restaurant_user_id = p_staff_id
     and restaurant_id = p_restaurant_id
     and salary_month = v_month;

  v_remaining := v_salary - v_paid;

  -- Refuse to overpay. The alternative — a negative "remaining" — would quietly
  -- corrupt both the payroll status and the outstanding-liability total.
  -- (Rounding slack matches the rest of the codebase.)
  if v_remaining <= 0.005 then
    raise exception 'ALREADY_PAID';
  end if;
  if p_amount > v_remaining + 0.005 then
    raise exception 'AMOUNT_EXCEEDS_REMAINING';
  end if;


  -- Resolve the tender split. No split given → single-tender, derived from the
  -- method, i.e. precisely what this function did before.
  if p_cash is null and p_online is null then
    v_cash   := case when p_method = 'cash' then p_amount else 0 end;
    v_online := case when p_method = 'cash' then 0 else p_amount end;
  else
    v_cash   := coalesce(p_cash, 0);
    v_online := coalesce(p_online, 0);
    if v_cash < 0 or v_online < 0 then
      raise exception 'INVALID_AMOUNT';
    end if;
    if abs((v_cash + v_online) - p_amount) > 0.005 then
      raise exception 'SPLIT_MISMATCH';
    end if;
    -- Absorb sub-paisa rounding into cash so cash + online = amount EXACTLY and
    -- the CHECK constraint holds. Without this a 33.333/66.667 split fails.
    v_cash := p_amount - v_online;
  end if;

  insert into salary_payments (
    restaurant_id, restaurant_user_id, salary_month, amount, kind, method,
    cash_amount, online_amount, notes, paid_by
  )
  values (
    p_restaurant_id, p_staff_id, v_month, p_amount, p_kind, p_method::payment_method,
    v_cash, v_online,
    nullif(btrim(coalesce(p_notes, '')), ''), p_by
  )
  returning id into v_id;

  return v_id;
end;
$function$
;

revoke all on function record_salary_payment(uuid, uuid, date, numeric, text, text, text, uuid, numeric, numeric) from public;
grant execute on function record_salary_payment(uuid, uuid, date, numeric, text, text, text, uuid, numeric, numeric) to service_role;
